### ISSUE TITLE
Reference algorithm

### ISSUE THREAD

**Issue by usergoodvery** [divfor/atomic_hash#1]
Hi

I was wondering if this implementation was based on some known or published algorithm?

Regards

**Comment by divfor** [comment]
Not published. it was done by myself: assuming selected hash function outputs 128-bits of 100% fair random, calculate: if plan loading n1 items to table 1 and n2 items out (not seated in 8 positions), then loading these n2 items to table 2 and n3 items out, at last append n3 items to a small scan-other-than-hash array. Now given n1 (max_nodes) and n3 (collision), calculate the best load factor r1, r2 for table 1, 2 with best memory usage. then get the tables length by n1/r1, n2/r2.

**Comment by usergoodvery** [comment]
OK. Have you worked out a proof of correctness?

**Comment by divfor** [comment]
I have tested it for hundred hours to get ride of possible segmentation fault with test code test/mthread_test.c, from single desktop 4-core CPU to two Xeon E5-2600 CPUs. The longest test run without segmentation fault is 20+ days. The data for randomly hash add/get/delete is 1 Million ~ 1 Billion strings.
